---
name: buckedup-bottle-loop
description: |
  A 3d printable loop for blender / bucked up bottles

  Ever get tied of your protein shake not having a carabiner loop? 3d print your own in TPU.
  Designed specifically for the bucked up perfect shaker

license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2022
resources:
  Perfect Shaker: https://www.buckedup.com/product/perfect-shaker
# fusion_link: https://autodesk.example.com #comment out if no fusion link
links:
  Thingiverse: https://www.thingiverse.com/thing:5201710
  Prusa: https://www.prusaprinters.org/prints/119261-bucked-up-bottle-loop
  # GrabCad: https://foo.com
  # Hackster.io: https://hackster.io/foo
  # Hackaday: https://hackaday.io/foo
  # Reddit: https://www.reddit.com/r/foo
  Github: https://github.com/spuder/buckedup-bottle-loop
  # Blog: https://foo.com
